config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :publications do
    collection do
      get "ofertas", to:"publications#ofertas"
      get "demandas", to: "publications#demandas"
    end
    resources :operations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dte.rb
class Dte < ApplicationRecord
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :publication
end

app/models/publication.rb
class Publication < ApplicationRecord
  validates :categoria, presence: true
  has_many :operations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]

  def index
    @operations = Operation.all
  end

  def show
  end

  def new
    @operation = Operation.new
  end

  def create
    Operation.create(operation_params)
    redirect_to operations_path
  end

  def edit
  end

  def update
    @operation.update(operation_params)
    redirect_to operations_path(@operation)
  end

  def destroy
    @operation.destroy
    redirect_to operations_path
  end

  private

  def operation_params
    params.require(:operation).permit(:nota)
  end

  def set_operation
    @operation = Operation.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController

  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  def ofertas
    @ofertas = Publication.where(oferta: 1)
  end

  def demandas
    @demandas = Publication.where(demanda: 1)
  end

  def index
    @publications = Publication.all
  end

  def show
  end

  def new
    @publication = Publication.new
  end

  def create
    Publication.create(publication_params)
    redirect_to publications_path
  end

  def edit
  end

  def update
    @publication.update(publication_params)
    redirect_to publications_path(@publication)
  end

  def destroy
    @publication.destroy
    redirect_to publications_path
  end

  private

  def publication_params
    params.require(:publication).permit(:categoria, :cantidad, :raza, :oferta, :demanda)
  end

  def set_publication
    @publication = Publication.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

<h1>Bienvenido</h1>

<img src="https://www.quo.es/wp-content/uploads/2019/10/por-que-las-vacas-atacan-a-mas-gente-que-los-toros.jpg">

<h2><%= link_to "Todas las publicaciones", publications_path %></h2>
<h2><%= link_to "Todas las ofertas",  ofertas_publications_path %></h2>
<h2><%= link_to "Todas las demandas",  demandas_publications_path %></h2>


    </div>
  </div>
</div>

app/views/publications/_form.html.erb
<div class="form">
  <%= form_for @publication do |f| %>
      <p><%= f.label :categoria, "Categoria" %>
      <%= f.text_field :categoria %></p>
      <p><%= f.label :cantidad, "Cantidad" %>
      <%= f.text_field :cantidad %></p>
      <p><%= f.label :raza, "Raza" %>
      <%= f.text_field :oferta %></p>
      <p>completa con 1 el que corresponda</p>
      <p><%= f.label :oferta, "Oferta" %>
      <%= f.text_field :oferta %></p>
      <p><%= f.label :demanda, "Demanda" %>
      <%= f.text_field :demanda %></p>
      <%= f.submit %>

  <% end %>
</div>

app/views/publications/demandas.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">


    <h1>Demandas</h1>

    <ul>
      <% @demandas.each do |publication| %>
        <li><h2>Categoria: <%= link_to publication.categoria, publication_path(publication) %></h2>
        <p>Cantidad: <%= publication.cantidad %></p>
        <p>Raza: <%= publication.raza %></p></li>
      <% end %>
    </ul>
    <%= link_to "Nueva publicacion", new_publication_path %>
    </div>
  </div>
</div>

app/views/publications/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

      <%=  render "form" %>
      <%= link_to "volver a todas las publicaciones", publications_path %>

    </div>
  </div>
</div>

app/views/publications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

      <h1>Todas las publicaciones</h1>

      <% @publications.each do |publication| %>

        <h2>Categoria: <%= link_to publication.categoria, publication_path(publication) %></h2>
        <p>Cantidad: <%= publication.cantidad %></p>
        <p>Raza: <%= publication.raza %></p>
        <%= link_to "Editar una publicacion |", edit_publication_path(publication) %>
        <%= link_to "Eliminar una publicacion", publication_path(publication), method: :delete %>
        <p>------------</p>

      <% end %>

      <%= link_to "Nueva publicacion", new_publication_path %>

    </div>
  </div>
</div>

app/views/publications/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

      <%=  render "form" %>
      <%= link_to "volver a todas las publicaciones", publications_path %>

    </div>
  </div>
</div>

app/views/publications/ofertas.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

    <h1>Ofertas</h1>
    <ul>
      <% @ofertas.each do |publication| %>
        <li><h2>Categoria: <%= link_to publication.categoria, publication_path(publication) %></h2>
        <p>Cantidad: <%= publication.cantidad %></p>
        <p>Raza: <%= publication.raza %></p></li>
      <% end %>
    </ul>

    <%= link_to "Nueva publicacion", new_publication_path %>
    </div>
  </div>
</div>

app/views/publications/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

      <h2>Categoria: <%= @publication.categoria %></h2>
      <p>Cantidad: <%= @publication.cantidad %></p>
      <p>Raza: <%= @publication.raza %></p>

      <%= link_to "Volver a todas las publicaciones", publications_path %>

    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://cdn2.iconfinder.com/data/icons/mammals-2/50/Cow-512.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Inicio", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mensajes", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://justice.org.au/wp-content/uploads/2017/08/avatar-icon.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Accion1", "#", class: "dropdown-item" %>
            <%= link_to "Accion2", "#", class: "dropdown-item" %>
            <%= link_to "Salir", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Ingresar", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>